# This file configures the code-style checks and runs unittests before code changes are git committed and pushed to Github (the file setup.cfg contains additional settings)
# After git cloning this repo please install all requirements in requirements.txt and requirements-dev.txt and then execute "pre-commit install"
# Article that explains this: https://towardsdatascience.com/4-pre-commit-plugins-to-automate-code-reviewing-and-formatting-in-python-c80c6d2e9f5

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: [ '--autofix' ]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [ --ignore-missing-imports ]
        additional_dependencies: [ types-pytz==2023.3.1.1, types-requests==2.31.0.4 ]
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [ --preview ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
      - id: pycln
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [ -vv, -i, --fail-under=80 ]
#  - repo: https://github.com/pycqa/pylint
#    rev: "v2.17.5"
#    hooks:
#      - id: pylint
#        exclude: "[a-zA-Z]*/(migrations)/(.)*"
#        args: [ "--load-plugins=pylint_django", "--django-settings-module=feed_aggregator.settings" ]
#        additional_dependencies: [pylint_django,]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ "-iii", "-ll", '-q' ]
  - repo: local
    hooks:
      - id: unittests
        name: run unit tests
        entry: python -m unittest
        language: system
        pass_filenames: false
        args: [ "discover" ]
