name: Production Deployment
on:
  push:
    branches:
      - 'main'

jobs:

  autotag:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        node-version:
        - 12
    steps:
      - uses: phish108/autotag-action@v1.1.64
        id: tagger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: TRUE
          branch: main
          release-branch: main
    outputs:
       new_version: ${{steps.tagger.outputs.new-tag}}

  docker:
    runs-on: ubuntu-latest
    needs: autotag
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
           context: .
           platforms: linux/arm64/v8,linux/amd64
           push: true
           tags: ${{secrets.DOCKER_USER}}/news_platform:latest,${{secrets.DOCKER_USER}}/news_platform:${{needs.autotag.outputs.new_version}}
